# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBRqlC3wmC1PddzxynRfRzRIF9WDw65O
"""

# fetch.py
import requests
import pandas as pd
from datetime import datetime, timedelta
import time
import os
import hopsworks

# ===== CONFIG =====
API_KEY = "6094f98aa9ad646bfcbdd49788573e5b"  # replace with your API key
LAT, LON = 24.8607, 67.0011
CITY_ID = 1174872
CSV_PATH = "karachi_weather_5hourly.csv"
FEATURE_GROUP_NAME = "karachi_aqi"
FEATURE_GROUP_VERSION = 1

# ===== FUNCTIONS =====
def fetch_weather_at(timestamp):
    url = "http://history.openweathermap.org/data/2.5/history/city"
    params = {
        "id": CITY_ID,
        "type": "hour",
        "start": int(timestamp.timestamp()),
        "end": int((timestamp + timedelta(hours=1)).timestamp()),
        "appid": API_KEY
    }
    r = requests.get(url, params=params)
    if r.status_code == 200 and r.json().get("list"):
        return r.json()["list"][0]
    else:
        print(f"⚠ Weather API error {r.status_code} at {timestamp}")
        return None

def fetch_pollution_at(timestamp):
    url = f"https://api.openweathermap.org/data/2.5/air_pollution/history"
    params = {
        "lat": LAT,
        "lon": LON,
        "start": int(timestamp.timestamp()),
        "end": int((timestamp + timedelta(hours=1)).timestamp()),
        "appid": API_KEY
    }
    r = requests.get(url, params=params)
    if r.status_code == 200 and r.json().get("list"):
        return r.json()["list"][0]
    else:
        print(f"⚠ Pollution API error {r.status_code} at {timestamp}")
        return None

def build_record(timestamp, previous_aqi=None):
    weather = fetch_weather_at(timestamp)
    pollution = fetch_pollution_at(timestamp)
    time.sleep(1)  # avoid rate limits

    if not weather or not pollution:
        return None

    comp = pollution["components"]
    record = {
        "timestamp": timestamp.strftime("%Y-%m-%d %H:%M:%S"),
        "aqi": pollution["main"]["aqi"],
        "pm2_5": comp["pm2_5"],
        "pm10": comp["pm10"],
        "temperature": round(weather["main"]["temp"] - 273.15, 2),
        "humidity": weather["main"]["humidity"],
        "wind_speed": weather["wind"]["speed"],
        "day": timestamp.day,
        "month": timestamp.month,
        "hour": timestamp.hour
    }

    # AQI change (difference from previous record)
    if previous_aqi is not None:
        record["aqi_change"] = record["aqi"] - previous_aqi
    else:
        record["aqi_change"] = 0

    return record

def save_records(records):
    df = pd.DataFrame(records)
    if os.path.exists(CSV_PATH):
        old = pd.read_csv(CSV_PATH)
        df = pd.concat([old, df], ignore_index=True)
        df.drop_duplicates(subset=["timestamp"], inplace=True)
    df.to_csv(CSV_PATH, index=False)
    print(f"✅ Saved {len(df)} total records to {CSV_PATH}")

    # Upload to Hopsworks Feature Store
    try:
        project = hopsworks.login()
        fs = project.get_feature_store()
        fg = fs.get_or_create_feature_group(
            name=FEATURE_GROUP_NAME,
            version=FEATURE_GROUP_VERSION,
            primary_key=["timestamp"],
            description="5-hourly Karachi weather + AQI + PM features",
            online_enabled=True
        )
        fg.insert(df, write_options={"wait_for_job": True})
        print(f"✅ Data uploaded to Hopsworks Feature Group: {FEATURE_GROUP_NAME}")
    except Exception as e:
        print(f"⚠ Hopsworks upload failed: {e}")

# ===== MAIN =====
def collect_5hourly_data(days_back=365):
    now = datetime.now()
    start = now - timedelta(days=days_back)
    records = []
    previous_aqi = None

    while start < now:
        print(f"📦 Fetching {start}")
        record = build_record(start, previous_aqi)
        if record:
            records.append(record)
            previous_aqi = record["aqi"]
        start += timedelta(hours=5)

    save_records(records)

# ===== RUN =====
if __name__ == "__main__":
    collect_5hourly_data()
