# -*- coding: utf-8 -*-
"""predict_aqi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBRqlC3wmC1PddzxynRfRzRIF9WDw65O
"""

# predict_aqi.py
import requests
import pandas as pd
import datetime
import pickle

# 1️⃣ Load trained model and scaler
with open("best_model.pkl", "rb") as f:
    model = pickle.load(f)

with open("scaler.pkl", "rb") as f:
    scaler = pickle.load(f)

# 2️⃣ Config
API_KEY = "6094f98aa9ad646bfcbdd49788573e5b"  # replace with your key
LAT, LON = 24.8607, 67.0011  # Karachi coordinates

# 3️⃣ Fetch 5-day weather forecast
weather_url = f"https://api.openweathermap.org/data/2.5/forecast?lat={LAT}&lon={LON}&appid={API_KEY}&units=metric"
weather_res = requests.get(weather_url).json()

weather_records = []
for entry in weather_res['list']:
    ts = datetime.datetime.fromtimestamp(entry['dt'])
    weather_records.append({
        "timestamp": ts,
        "temperature": entry['main']['temp'],
        "humidity": entry['main']['humidity'],
        "wind_speed": entry['wind']['speed'],
        "hour": ts.hour,
        "day": ts.day,
        "month": ts.month
    })

df_weather = pd.DataFrame(weather_records)
print(f"✅ Weather forecast records fetched: {len(df_weather)}")

# 4️⃣ Fetch PM2.5 and PM10 for the same timestamps
pm_records = []
for ts in df_weather['timestamp']:
    unix_ts = int(ts.timestamp())
    air_url = f"http://api.openweathermap.org/data/2.5/air_pollution/history?lat={LAT}&lon={LON}&start={unix_ts}&end={unix_ts}&appid={API_KEY}"
    air_res = requests.get(air_url).json()

    if air_res.get('list'):
        pm2_5 = air_res['list'][0]['components']['pm2_5']
        pm10  = air_res['list'][0]['components']['pm10']
    else:
        pm2_5, pm10 = None, None

    pm_records.append({"timestamp": ts, "pm2_5": pm2_5, "pm10": pm10})

df_pm = pd.DataFrame(pm_records)

# 5️⃣ Merge weather and PM data
df_forecast = pd.merge(df_weather, df_pm, on="timestamp", how="left")
df_forecast['pm2_5'] = df_forecast['pm2_5'].fillna(method='ffill')
df_forecast['pm10']  = df_forecast['pm10'].fillna(method='ffill')

# 6️⃣ Scale features
feature_cols = ['pm2_5', 'pm10', 'temperature', 'humidity', 'wind_speed', 'hour', 'day', 'month']
df_forecast[feature_cols] = scaler.transform(df_forecast[feature_cols])

# 7️⃣ Predict AQI
df_forecast['predicted_aqi'] = model.predict(df_forecast[feature_cols])

# 8️⃣ Save results
df_forecast.to_csv("future_aqi_forecast.csv", index=False)
print("✅ Future AQI predictions saved!")
print(df_forecast[['timestamp', 'predicted_aqi']].head())