# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBRqlC3wmC1PddzxynRfRzRIF9WDw65O
"""

# preprocess.py
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import pickle

def preprocess_data(file_path="raw_data.csv", save_scaler=True):
    df = pd.read_csv(file_path)

    # 1Remove duplicates
    df = df.drop_duplicates()

    # 2 Handle missing values (fill with median as example)
    for col in ['pm2_5', 'pm10', 'temperature', 'humidity', 'wind_speed', 'aqi']:
        if col in df.columns:
            df[col].fillna(df[col].median(), inplace=True)

    # 3️ Cap outliers using IQR
    numeric_cols = ['pm2_5', 'pm10', 'temperature', 'humidity', 'wind_speed', 'aqi']
    for col in numeric_cols:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        df[col] = df[col].clip(lower, upper)

    # 4️ Derived feature: AQI change
    if "aqi" in df.columns:
        df["aqi_change"] = df["aqi"].diff().fillna(0)

    # 5️ Scale numerical features
    scale_cols = ['pm2_5', 'pm10', 'temperature', 'humidity', 'wind_speed', 'hour', 'day', 'month']
    scaler = MinMaxScaler()
    df[scale_cols] = scaler.fit_transform(df[scale_cols])

    if save_scaler:
        with open("scaler.pkl", "wb") as f:
            pickle.dump(scaler, f)
        print(" Scaler saved as scaler.pkl")

    df.to_csv("processed_data.csv", index=False)
    print(" Data preprocessed, outliers capped, and saved as processed_data.csv")

    return df, scaler

if __name__ == "__main__":
    preprocess_data()