# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBRqlC3wmC1PddzxynRfRzRIF9WDw65O
"""

# train_model.py
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import pickle
import numpy as np

# 1️⃣ Load preprocessed data
df = pd.read_csv("processed_data.csv")

# 2️⃣ Split into features and target
feature_cols = ['pm2_5', 'pm10', 'temperature', 'humidity', 'wind_speed', 'hour', 'day', 'month']
X = df[feature_cols]
y = df['aqi']

# 3️⃣ Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4️⃣ Define models
models = {
    "RandomForest": RandomForestRegressor(n_estimators=100, random_state=42),
    "LinearRegression": LinearRegression()
}

best_model = None
best_r2 = -np.inf

# 5️⃣ Train & evaluate models
for name, model in models.items():
    model.fit(X_train, y_train)
    preds = model.predict(X_test)

    r2 = r2_score(y_test, preds)
    mae = mean_absolute_error(y_test, preds)
    rmse = mean_squared_error(y_test, preds) ** 0.5  # compatible with older sklearn versions

    print(f"\n{name} Performance:")
    print(f"R² Score: {r2:.4f}")
    print(f"MAE: {mae:.4f}")
    print(f"RMSE: {rmse:.4f}")

    if r2 > best_r2:
        best_r2 = r2
        best_model = model

# 6️⃣ Save the best model
with open("best_model.pkl", "wb") as f:
    pickle.dump(best_model, f)

print("\n✅ Best model saved as best_model.pkl")